production:
    delivery_method: :smtp
    smtp_settings:
      address: smtp.gmail.com
      port: 587
      tls: false
      domain: www.codus.com.br
      authentication: :plain
      user_name: vinicius.oyama@codus.com.br
      password: c0dus4321
